modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MrCrayfish/Director/issues"

[[mods]]
    modId="director"
    version="0.1.1"
    displayName="Director"
    updateJSONURL=""
    displayURL=""
    logoFile="director.png"
    credits="MrCrayfish"
    authors="MrCrayfish"
    description="A simple camera mod because everything else sucks!"

[[dependencies.director]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.director]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"
