modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/"
license="GPL3"

[[mods]]
    modId="director"
    version="0.1.1"
    displayName="Director"
    updateJSONURL="http://myurl.me/"
    displayURL="http://example.com/"
    logoFile="director.png"
    credits=""
    authors="MrCrayfish"
    description="A simple camera mod because nothing exists!"

[[dependencies.director]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.director]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"
